name: 'Shisito Markdown Validation'
description: 'Sweet and simple markdown field, type, and formatting validation and linting'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'check'
  color: 'red'
