name: 'Shisito Markdown Validation'
description: 'Simple and rich markdown field, type, and formatting validation'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'check'
  color: 'red'
