name: 'Shisito Markdown Validation'
description: 'Sweet, spicy, and rich markdown field, type, formatting validation and linting'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'check'
  color: 'red'
