name: CI
on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: run-tests
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: docker://docker
        with:
          args: docker build . --tag=shisito:latest
      - name: unit-tests
        uses: docker://docker
        with:
          args: docker run shisito:latest TEST           
      - name: integration-tests
        uses: docker://docker
        with:
          args: docker run -v /home/runner/work/shisito-markdown-validation/shisito-markdown-validation/test:/github/workspace shisito:latest RUN          