name: CI
on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: run-tests
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.8
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true 
      - name: docker-build
        uses: docker://docker
        with:
          args: docker build . --tag=shisito:latest
      - name: unit-tests
        uses: docker://docker
        with:
          args: docker run shisito:latest TEST           
      - name: integration-tests
        uses: docker://docker
        with:
          args: docker run -v /home/runner/work/shisito-markdown-validation/shisito-markdown-validation/integration:/github/workspace shisito:latest RUN          
